Implement check for account name existence in login dialog
hpi-swa-teaching/IMAPClient pull request #205
Opened 2019-06-05 19:16 UTC by EightSQ

This fixes #130.
I left the `displayAccountnameExistsErrorMessage` method unclassified, because other similar methods also are not classified yet.
I found some debt in this code region, see #204, so I would suggest addressing this within a small refactoring rather than at this point.

2019-06-05 19:28 UTC, martintaraz approved these changes

2019-06-06 07:25 UTC, timgarrels requested changes
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/205)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @EatingBacon, @EightSQ, @felixrindt, and @Paulpanther)

___
*[packages/IMAPClient-UI.package/ICLoginDialog.class/instance/checkForAccountnameExistence..st, line 9 at r1](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/205#-Lgff4d0EhBk-vFiOL0I:-Lgff4d1DKK3ecQNqrW7:brjc874) ([raw file](https://github.com/hpi-swa-teaching/imapclient/blob/a3105b97c3ab12b3243bf54bc224bdfea0a6bd4d/packages/IMAPClient-UI.package/ICLoginDialog.class/instance/checkForAccountnameExistence..st#L9)):*
> ```Smalltalk
> 			ifTrue: [
> 				self displayAccountnameExistsErrorMessage.
> 				^ false ].].
> ```

The method name suggests the following behavior: Name exists --> true, else --> false
The code itself does it exactly the other way around. I suggest a name change or a swap of these return values
___
*[packages/IMAPClient-UI.package/ICLoginDialog.class/instance/displayAccountnameExistsErrorMessage.st, line 1 at r1](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/205#-LgfcMXh2kwkQqU_LGFj:-LgfcMXi2N1iFJdhHkdD:b-ut5vsv) ([raw file](https://github.com/hpi-swa-teaching/imapclient/blob/a3105b97c3ab12b3243bf54bc224bdfea0a6bd4d/packages/IMAPClient-UI.package/ICLoginDialog.class/instance/displayAccountnameExistsErrorMessage.st#L1)):*
> ```Smalltalk
> as yet unclassified
> ```

Fitting Category missing. This is explained [here](https://github.com/hpi-swa-teaching/IMAPClient/pull/205#issue-285514245) , but the new code should be written in a fitting category, if no fitting category exists yet it should be created.


<!-- Sent from Reviewable.io -->

2019-06-06 07:43 UTC, felixrindt requested changes

2019-06-06 07:43 UTC, felixrindt commented on packages/IMAPClient-UI.package/ICLoginDialog.class/instance/checkIfAccountnameUnused..st
> +		((aDictionary at: 'name') = (credDict at: 'name'))
Maybe do `ICHelper loadCredentialsIntoDictionaries detect: [:credDict | (dict at: 'name') = (aDictionary at: 'name')] ifFound: [...] ifNone: [^true]`

2019-06-06 07:59 UTC, felixrindt approved these changes

2019-06-06 08:06 UTC, timgarrels approved these changes
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hpi-swa-teaching/imapclient/205)* status: all files reviewed, 3 unresolved discussions (waiting on @EightSQ and @Paulpanther)



<!-- Sent from Reviewable.io -->

2019-06-06 08:06 UTC, merged