Added Lazy init
hpi-swa-teaching/IMAPClient pull request #215
Opened 2019-06-09 11:36 UTC by Paulpanther

for ICEndPoint, ICFetchResponseParser, ICFolder, ICServerInfo, ICStreamWrapper, ICFolderDialog and ICLoginDialog

2019-06-20 06:44 UTC, timgarrels requested changes
`testRetrieveBody` fails due to timeout. This is rooted in the `ICFolder path` lazy init, which contains an potential endless lookup to parentfolder paths.
This *could* be fixed in the test by setting the dummy-folder to the dummy-endpoints rootFolder. But I do not have a sufficient overview over this part of ICEndpoints Functionality

2019-06-25 07:44 UTC, EatingBacon commented
As this is a week old now and noone seems to have more knowledge of this:

The `ICFolder` Class Comment states that 'parent:		The parent ICFolder. This is automatically filled in by the ICEndPoint.'
Removing the lazy-init of parent also makes all tests pass.
I suggest to file an issue concerning the flow of ICFolder and ICEndpoint paths and merge this without the lazy init for `ICFolder parent`

2019-06-25 19:34 UTC, timgarrels approved these changes

2019-06-27 10:16 UTC, felixrindt approved these changes

2019-06-27 12:09 UTC, merged