Issue81
hpi-swa-teaching/IMAPClient pull request #93
Opened 2018-05-25 20:53 UTC by mariwalt

Achtung: Dieser Branch hat fixing_leonard als Basis. Bevor wir diesen Branch jemals mergen, sollten wir erst fixing_leonard reviewen, Tests reparieren und mergen. 

Was hat sich hier geändert: 
1) Emails lassen sich nun deutlich schneller runterladen/anzeigen
2) Löschen von Emails ist möglich

Achtung: wenn ihr nun eine Email löscht, dann ist diese endgültig weg! Also seid vorsichtig beim Testen!!! 
Warum ist das so? Das Löschen mittels Imap geht über zwei Schritte:
1) Man gibt einer Emails das Flag \Delete. (Bis hierhin passiert also gar nichts auf dem Server - nichts wird gelöscht, verschoben oder so. Es wird nur ein Flag gesetzt.)
2) Nun sendet man das Kommando Expunge an der Server. Damit werden alle Emails mit den Flag \Delete im aktuellen Ordner endgültig gelöscht.

Eine gute Lösung wäre also, dass wir zwischen den beiden Schritten die Emails mit den Flag \Delete in den Thrash-Ordner verschieben. Und dort führen wir dann das Expunge-Kommando aus. Da wir aber noch nicht Emails verschieben können, müssen wir uns mit der derzeitigen Lösung erstmal zufrieden geben.

2018-05-28 17:23 UTC, davidhennemann commented
Will review tomorrow. Sorry was a little bit busy at weekend 😄

2018-06-02 10:13 UTC, davidhennemann requested changes
Nearly everthing is fine. (Only a few points --> see reviews)
Can you merge develop into your branch?
I will fix tests for you :)

2018-06-02 10:13 UTC, davidhennemann commented on packages/IMAPClient-Core.package/ICEndPoint.class/instance/parseFetchFlags.for..st
> +	((aHeaderChunk at: 1) includesSubstring: '\Seen')
I would suggest: `anEmail seen: ((aHeaderChunk at: 1) includesSubstring: '\Seen')`. No need for the conditional logic :)

2018-06-02 10:13 UTC, davidhennemann commented on packages/IMAPClient-Core.package/ICEndPoint.class/instance/parseFetchFlags.for..st
> +	((aHeaderChunk at: 1) includesSubstring: '\Flagged')
see above

2018-06-02 10:29 UTC, mariwalt commented
?ups, those are good changes!


I merged develop in it and pushed it!

________________________________
From: DavidHenn <notifications@github.com>
Sent: 02 June 2018 12:13
To: hpi-swa-teaching/IMAPClient
Cc: Walter, Marius; Author
Subject: Re: [hpi-swa-teaching/IMAPClient] Issue81 (#93)


@davidhennemann requested changes on this pull request.

Nearly everthing is fine. (Only a few points --> see reviews)
Can you merge develop into your branch?
I will fix tests for you :)

________________________________

In packages/IMAPClient-Core.package/ICEndPoint.class/instance/parseFetchFlags.for..st<https://github.com/hpi-swa-teaching/IMAPClient/pull/93#discussion_r192555818>:

> @@ -0,0 +1,13 @@
+protocol parse
+parseFetchFlags: aHeaderChunk for: anEmail
+
+       ((aHeaderChunk at: 1) includesSubstring: '\Seen')


I would suggest: anEmail seen: ((aHeaderChunk at: 1) includesSubstring: '\Seen'). No need for the conditional logic :)

________________________________

In packages/IMAPClient-Core.package/ICEndPoint.class/instance/parseFetchFlags.for..st<https://github.com/hpi-swa-teaching/IMAPClient/pull/93#discussion_r192555828>:

> @@ -0,0 +1,13 @@
+protocol parse
+parseFetchFlags: aHeaderChunk for: anEmail
+
+       ((aHeaderChunk at: 1) includesSubstring: '\Seen')
+               ifTrue: [anEmail seen: true]
+               ifFalse: [anEmail seen: false].
+
+       ((aHeaderChunk at: 1) includesSubstring: '\Flagged')


see above

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/hpi-swa-teaching/IMAPClient/pull/93#pullrequestreview-125361939>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AXwqYcbVorOE5EZcy6KbsVTL5i-6WKS-ks5t4mUxgaJpZM4UOkA5>.

2018-06-02 11:16 UTC, davidhennemann requested changes
Okay, i fixed the tests :) Just had to add some flags to the test data. But i noticed an issue. 
Steps to reproduce:
1. Mark a Mail as Unseen
![image](https://user-images.githubusercontent.com/6185006/40873743-8feb1cb6-6666-11e8-8b2e-589c45d9908b.png)
2. Close Mail Client, and reopen it.
3. Dont update from Server, just use the already loaded version. Now the Mail wont display the [UNSEEN] Flag, but seems still to be unread, because right clicking it, gives me the option to `Mark as seen`.
![image](https://user-images.githubusercontent.com/6185006/40873769-ef6e7002-6666-11e8-9a1a-0c3ca4120f72.png)

I think you need to add the [UNSEEN] in front of the name if mails get loaded from storage to fix this :) 
Even pressing the update button, wont get the [UNSEEN] Flag back...its just stays as it is. But the Content Menu still says `Mark as seen`. So i think its just a rendering issue.

2018-06-02 11:16 UTC, davidhennemann commented on packages/IMAPClient-Core.package/ICFileReadWriter.class/instance/get.in..st
> +		seen: (jsonFile at: 'seen');
`seen` and `flagged` are header informations, those will be loaded within header: `(self createHeaderFrom: (jsonFile at: 'header'));`. There are only present in the jsonFile 'header' field, setting them here, will result in always setting them to `nil`. Couldnt have figured this out without the test...wow maybe tests are helpful at all :D will fix this within my commit, which will fix the tests. :)

2018-06-02 12:20 UTC, mariwalt commented
It's fixed now?.

________________________________
From: DavidHenn <notifications@github.com>
Sent: 02 June 2018 13:16
To: hpi-swa-teaching/IMAPClient
Cc: Walter, Marius; Author
Subject: Re: [hpi-swa-teaching/IMAPClient] Issue81 (#93)


@davidhennemann requested changes on this pull request.

Okay, i fixed the tests :) Just had to add some flags to the test data. But i noticed an issue.
Steps to reproduce:

  1.  Mark a Mail as Unseen
[image]<https://user-images.githubusercontent.com/6185006/40873743-8feb1cb6-6666-11e8-8b2e-589c45d9908b.png>
  2.  Close Mail Client, and reopen it.
  3.  Dont update from Server, just use the already loaded version. Now the Mail wont display the [UNSEEN] Flag, but seems still to be unread, because right clicking it, gives me the option to Mark as seen.
[image]<https://user-images.githubusercontent.com/6185006/40873769-ef6e7002-6666-11e8-9a1a-0c3ca4120f72.png>

I think you need to add the [UNSEEN] in front of the name if mails get loaded from storage to fix this :)
Even pressing the update button, wont get the [UNSEEN] Flag back...its just stays as it is. But the Content Menu still says Mark as seen. So i think its just a rendering issue.

________________________________

In packages/IMAPClient-Core.package/ICFileReadWriter.class/instance/get.in..st<https://github.com/hpi-swa-teaching/IMAPClient/pull/93#discussion_r192556867>:

> @@ -8,5 +8,7 @@ get: aFile in: aFolder
                header: (self createHeaderFrom: (jsonFile at: 'header'));
                body: (jsonFile at: 'body');
                messageID: (jsonFile at: 'messageID');
+               seen: (jsonFile at: 'seen');


seen and flagged are header informations, those will be loaded within header: (self createHeaderFrom: (jsonFile at: 'header'));. There are only present in the jsonFile 'header' field, setting them here, will result in always setting them to nil. Couldnt have figured this out without the test...wow maybe tests are helpful at all :D will fix this within my commit, which will fix the tests. :)

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/hpi-swa-teaching/IMAPClient/pull/93#pullrequestreview-125362364>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AXwqYQobp3NYf7N-XT4hlSVKftughpM7ks5t4nQkgaJpZM4UOkA5>.

2018-06-02 12:42 UTC, davidhennemann commented
Yeah, it works flawlessly now :) Should we merge this one?

2018-06-02 12:42 UTC, davidhennemann approved these changes

2018-06-02 12:48 UTC, davidhennemann commented
Okay, still found an issue, but i am not sure, whether we need an extra issue for that. 

1. Mark an Mail as unseen.
2. Read mail on another device.
3. Mail is still marked as unseen, even after `Update`. The Update Button should also update flags for existing mails, shoudnt it? 

But we can create a sepeate issue for this, because we need to figure out a nice way, how to update already loaded mails.... What do you think?

2018-06-02 12:57 UTC, mariwalt commented
?In that case pressing update will load the locally stored email. And the locally stored email does not know about any changes on the other device. For similar reason I initially never stored and loaded the flags locally, but always loaded from the server (thus, there was never a reason to store them). But this caused bad performance, so I changed it in this issue again...

Maybe we should create another issue for this problem and solve it on another branch, but merge this branch already in develop.

________________________________
From: David Hennemann <notifications@github.com>
Sent: 02 June 2018 14:48
To: hpi-swa-teaching/IMAPClient
Cc: Walter, Marius; Author
Subject: Re: [hpi-swa-teaching/IMAPClient] Issue81 (#93)


Okay, still found an issue, but i am not sure, whether we need an extra issue for that.

  1.  Mark an Mail as unseen.
  2.  Read mail on another device.
  3.  Mail is still marked as unseen, even after Update. The Update Button should also update flags for existing mails, shoudnt it?

But we can create a sepeate issue for this, because we need to figure out a nice way, how to update already loaded mails.... What do you think?

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/hpi-swa-teaching/IMAPClient/pull/93#issuecomment-394085138>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AXwqYej6hl4MqznSJVT9fbCGAZRHSXd-ks5t4omggaJpZM4UOkA5>.

2018-06-02 13:11 UTC, davidhennemann commented
Okay, sounds good. We need to figure out a smart way how to update locally saved mails from the server, witout running into a bad performance. Created Follow-Up-Issue: https://github.com/hpi-swa-teaching/IMAPClient/issues/100

2018-06-02 13:11 UTC, merged